services:
  nginx-webdav:
    image: baksili/webdav-server:latest
    container_name: webdav
    ports:
      - "80:80/tcp"
    environment:
      - USERNAME=user
      - PASSWORD=pass

  sftp:
    image: atmoz/sftp
    volumes:
    - ./etc/socket-ssh:/etc/ssh/ssh_host_rsa
    - ./etc/localhost-rsa.pub:/home/foo/.ssh/keys/id_rsa.pub:ro
    - ./data:/home/foo/upload
    ports:
      - "1522:22"
    command: foo:pass:1000:::upload
