services:
  nginx-webdav:
    image: baksili/webdav-server:latest
    container_name: webdav
    ports:
      - "80:80/tcp"
    environment:
      - USERNAME=user
      - PASSWORD=pass

  sftp:
    image: atmoz/sftp
    volumes:
    - ./data:/home/foo/upload
    ports:
      - "1522:22"
    command: foo:pass:1000:::upload
