services:
  nginx-webdav:
    image: baksili/webdav-server:latest
    container_name: webdav
    ports:
      - "8080:80/tcp"
    volumes:
      - "./data:/media/data"
    environment:
      - USERNAME=user
      - PASSWORD=pass
