name: PHP Composer and Tests for WebDav using Docker

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

permissions:
  contents: read

jobs:
  build:
    name: PHP ${{ matrix.php-versions }} on ${{ matrix.os }} w/ ${{ matrix.dependencies }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        os: [ubuntu-latest]
        dependencies: ["install", "update"]
    env: 
      extensions: curl,openssl,ssh2,json,mbstring
      key: extensions-php

    steps:
      - uses: actions/checkout@main
      
      - name: Set up Docker
        uses: docker/setup-docker-action@master

      - name: Run Docker Compose
        run: docker compose up -d
      
      - name: Setup PHP
        id: php-env
        uses: shivammathur/setup-php@main
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          ini-values: 
          
      - name: Cache extensions
        uses: actions/cache@main
        with:
          path: vendor
          key: ${{ runner.os }}-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-versions }}-

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer ${{ matrix.dependencies }} --prefer-dist --no-progress --ignore-platform-reqs
        env:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          ini-values: 

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Run test suite
        env:
          TMPDIR: ${{ runner.temp }}
        run: vendor/bin/phpunit -c phpunit.xml tests/Functional/WebDavTest.php

      - name: Tear Down Docker Compose
        if: always()
        run: docker compose down
